# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-22 11:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='allSongs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artists', models.CharField(max_length=255)),
                ('song_url', models.FileField(upload_to='songs', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])])),
            ],
        ),
    ]
