# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_playlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='playListSongs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.playlist')),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.allSongs')),
            ],
        ),
    ]
